

#App Configuration
Application:
    AppNAme: Graphql-Api

#Server configurations
server:
    host: 127.0.0.1
    port: 8000

#Database configuration
database:
    username: "postgres"
    password: "password"
    dbname: "media"
    dbPort: 5432
    Sslmode: "disable"

#App security setting
security:
    privateKey: ""
    hash: